// 
// auto-generated by op2.m on 07-Apr-2010 12:41:20 
//

// header                  
                           
#include "op_lib.cu"       
                           
// global constants        
                           
__constant__ float  alpha; 
                           
// user kernel files       
                           
                           
#include "res_kernel.cu"   
#include "update_kernel.cu"
