// 
// auto-generated by op2.m on 12-Feb-2010 12:40:37 
//

// header files            
                           
#include <stdlib.h>        
#include <stdio.h>         
#include <string.h>        
#include <math.h>          
#include <cutil_inline.h>  
#include "op_datatypes.h"  
                           
// global constants        
                           
__constant__ float alpha;  
                           
// user kernel files       
                           
#include "res_kernel.cu"   
#include "update_kernel.cu"
