// 
// auto-generated by op2.m on 02-Jan-2011 15:30:15 
//

// header                   
                            
#include "op_lib.cpp"       
                            
// global constants         
                            
extern float alpha;         
                            
// user kernel files        
                            
#include "res_kernel.cpp"   
#include "update_kernel.cpp"
