#
# set paths for header files and libraries
#

CUDA		:= $(CUDA_INSTALL_PATH)
INC		:= -I$(CUDA)/include -I.
LIB		:= -L$(CUDA)/lib64

#
# set flags for compilation and linking
#

CCFLAGS		:= -g -fPIC -DUNIX -Wall -Wextra
NVCCFLAGS	:= -g -G -arch=sm_20 -Xptxas=-v -use_fast_math
LIBS		:= -lcudart

#
# master to make all versions
#

all:		jac_seq jac_op jac_cuda

#
# simple sequential version
#

jac_seq:	jac.cpp op_seq.cpp op_datatypes.h
		g++ -o jac_seq jac.cpp op_seq.cpp

#
# x86 version using kernel files generated by op2.m
#

jac_op:		jac_op.cpp jac_kernels.cpp op_datatypes.h \
		res_kernel.cpp update_kernel.cpp \
		res.h          update.h
		g++ -o jac_op jac_op.cpp jac_kernels.cpp

#
# CUDA version using kernel files generated by op2.m
#

jac_cuda:	jac_op.o jac_kernels.o
		g++ -fPIC -o jac_cuda jac_op.o jac_kernels.o $(LIB) $(LIBS)

jac_op.o:	jac_op.cpp op_datatypes.h
		g++ -c $(CCFLAGS) -o jac_op.o jac_op.cpp

jac_kernels.o:	jac_kernels.cu op_lib.cu op_datatypes.h \
		res_kernel.cu update_kernel.cu \
		res.h         update.h
		nvcc -c $(INC) $(NVCCFLAGS) -o jac_kernels.o jac_kernels.cu

#
# cleanup
#

clean:
		rm -f jac_seq jac_op jac_cuda jac_op.o jac_kernels.o

#
# make tar file
#

tar_file:	
		tar cvf op2.tar *.cpp *.h *.cu *.m Makefile \
		                *.tex *.pdf README TO_DO airfoil
