// 
// auto-generated by op2.m on 31-Oct-2010 15:01:42 
//

// user function                                                                         
                                                                                         
#include "res.h"                                                                         
                                                                                         
                                                                                         
// x86 kernel function                                                                   
                                                                                         
void op_x86_res(                                                                         
  int    blockIdx,                                                                       
  float *ind_arg0, int *ind_arg0_ptrs, int *ind_arg0_sizes, int *ind_arg0_offset,        
  float *ind_arg1, int *ind_arg1_ptrs, int *ind_arg1_sizes, int *ind_arg1_offset,        
  double *arg0_d,                                                                        
  int   *arg1_ptrs,                                                                      
  int   *arg2_ptrs,                                                                      
  const float *arg3,                                                                     
  int    block_offset,                                                                   
  int   *blkmap,                                                                         
  int   *offset,                                                                         
  int   *nelems,                                                                         
  int   *ncolors,                                                                        
  int   *colors) {                                                                       
                                                                                         
  float arg2_l[1];                                                                       
                                                                                         
  int   *ind_arg0_ptr, ind_arg0_size;                                         
  int   *ind_arg1_ptr, ind_arg1_size;                                         
  float *ind_arg0_s;                                                          
  float *ind_arg1_s;                                                          
  double *arg0;                                                               
  int   *arg1_ptr;                                                            
  int   *arg2_ptr;                                                            
  int    nelems2, ncolor, *color;                                             
  int    blockId, nelem;                                                      
                                                                                         
  char shared[64000];                                                         
                                                                                         
  if (0==0) {                                                                            
                                                                                         
    // get sizes and shift pointers and direct-mapped data                               
                                                                                         
    blockId = blkmap[blockIdx + block_offset];                                           
    nelem   = nelems[blockId];                                                           
                                                                                         
    nelems2 = nelem;                                                                     
    ncolor  = ncolors[blockId];                                                          
    color   = colors + offset[blockId];                                                  
                                                                                         
    ind_arg0_size = ind_arg0_sizes[blockId];                                             
    ind_arg1_size = ind_arg1_sizes[blockId];                                             
                                                                                         
    ind_arg0_ptr = ind_arg0_ptrs + ind_arg0_offset[blockId];                             
    ind_arg1_ptr = ind_arg1_ptrs + ind_arg1_offset[blockId];                             
                                                                                         
    arg0         = arg0_d    + offset[blockId]*1;                                        
    arg1_ptr     = arg1_ptrs + offset[blockId];                                          
    arg2_ptr     = arg2_ptrs + offset[blockId];                                          
                                                                                         
    // set shared memory pointers                                                        
                                                                                         
    int nbytes = 0;                                                                      
    ind_arg0_s = (float *) &shared[nbytes];                                              
    nbytes    += ROUND_UP(ind_arg0_size*sizeof(float)*1);                                
    ind_arg1_s = (float *) &shared[nbytes];                                              
  }                                                                                      
                                                                                         
  __syncthreads(); // make sure all of above completed                                   
                                                                                         
  // copy indirect datasets into shared memory or zero increment                         
                                                                                         
  for (int n=0; n<ind_arg0_size; n++)                                                    
    for (int d=0; d<1; d++)                                                              
      ind_arg0_s[d+n*1] = ind_arg0[d+ind_arg0_ptr[n]*1];                                 
                                                                                         
  for (int n=0; n<ind_arg1_size; n++)                                                    
    for (int d=0; d<1; d++)                                                              
      ind_arg1_s[d+n*1] = ZERO_float;                                                    
                                                                                         
  __syncthreads();                                                                       
                                                                                         
  // process set elements                                                                
                                                                                         
  for (int n=0; n<nelems2; n++) {                                                        
    int col2 = -1;                                                                       
                                                                                         
    if (n<nelem) {                                                                       
                                                                                         
      // initialise local variables                                                      
                                                                                         
      for (int d=0; d<1; d++)                                                            
        arg2_l[d] = ZERO_float;                                                          
                                                                                         
      // user-supplied kernel call                                                       
                                                                                         
      res( arg0+n*1,                                                                     
           ind_arg0_s+arg1_ptr[n]*1,                                                     
           arg2_l,                                                                       
           arg3 );                                                                       
                                                                                         
      col2 = color[n];                                                                   
    }                                                                                    
                                                                                         
    // store local variables                                                             
                                                                                         
    for (int col=0; col<ncolor; col++) {                                                 
      if (col2==col) {                                                                   
        for (int d=0; d<1; d++)                                                          
          ind_arg1_s[d+arg2_ptr[n]*1] += arg2_l[d];                                      
      }                                                                                  
      __syncthreads();                                                                   
    }                                                                                    
                                                                                         
  }                                                                                      
                                                                                         
  // apply pointered write/increment                                                     
                                                                                         
  for (int n=0; n<ind_arg1_size; n++)                                                    
    for (int d=0; d<1; d++)                                                              
      ind_arg1[d+ind_arg1_ptr[n]*1] += ind_arg1_s[d+n*1];                                
                                                                                         
}                                                                                        
                                                                                         
                                                                                         
// host stub function                                                                    
                                                                                         
void op_par_loop_res(char const *name, op_set set,                                       
  op_dat arg0, int idx0, op_ptr ptr0, int dim0, char const *typ0, op_access acc0,        
  op_dat arg1, int idx1, op_ptr ptr1, int dim1, char const *typ1, op_access acc1,        
  op_dat arg2, int idx2, op_ptr ptr2, int dim2, char const *typ2, op_access acc2,        
  float *arg3h,int idx3, op_ptr ptr3, int dim3, char const *typ3, op_access acc3){       
                                                                                         
  op_dat arg3 = {{0,0,"null"},0,0,0,(char *)arg3h,NULL,"float","gbl"};                   
                                                                                         
  int         nargs = 4, ninds = 2;                                                      
                                                                                         
  op_dat      args[4] = {arg0,arg1,arg2,arg3};                                           
  int         idxs[4] = {idx0,idx1,idx2,idx3};                                           
  op_ptr      ptrs[4] = {ptr0,ptr1,ptr2,ptr3};                                           
  int         dims[4] = {dim0,dim1,dim2,dim3};                                           
  char const *typs[4] = {typ0,typ1,typ2,typ3};                                           
  op_access   accs[4] = {acc0,acc1,acc2,acc3};                                           
  int         inds[4] = {-1,0,1,-1};                                                     
                                                                                         
  if (OP_diags>2) {                                                                      
    printf(" kernel routine with indirection: res \n");                                  
  }                                                                                      
                                                                                         
  // initialise timers                                                                   
                                                                                         
  double cpu_t1, cpu_t2, wall_t1, wall_t2;                                               
  timers(&cpu_t1, &wall_t1);                                                             
                                                                                         
  // set number of threads                                                               
                                                                                         
#ifdef _OPENMP                                                                           
  int nthreads = omp_get_max_threads( );                                                 
#else                                                                                    
  int nthreads = 1;                                                                      
#endif                                                                                   
                                                                                         
  // get plan                                                                            
                                                                                         
  op_plan *Plan = plan(name,set,nargs,args,idxs,ptrs,dims,typs,accs,ninds,inds);         
                                                                                         
  // execute plan                                                                        
                                                                                         
  int block_offset = 0;                                                                  
                                                                                         
  for (int col=0; col<(*Plan).ncolors; col++) {                                          
    int nblocks = (*Plan).ncolblk[col];                                                  
                                                                                         
#pragma omp parallel for                                                                 
    for (int blockIdx=0; blockIdx<nblocks; blockIdx++)                                   
     op_x86_res( blockIdx,                                                               
       (float *)arg1.dat, (*Plan).ind_ptrs[0], (*Plan).ind_sizes[0], (*Plan).ind_offs[0],
       (float *)arg2.dat, (*Plan).ind_ptrs[1], (*Plan).ind_sizes[1], (*Plan).ind_offs[1],
       (double *)arg0.dat,                                                               
       (*Plan).ptrs[1],                                                                  
       (*Plan).ptrs[2],                                                                  
       (float *)arg3.dat,                                                                
       block_offset,                                                                     
       (*Plan).blkmap,                                                                   
       (*Plan).offset,                                                                   
       (*Plan).nelems,                                                                   
       (*Plan).nthrcol,                                                                  
       (*Plan).thrcol);                                                                  
                                                                                         
    block_offset += nblocks;                                                             
  }                                                                                      
                                                                                         
  // update kernel record                                                                
                                                                                         
  timers(&cpu_t2, &wall_t2);                                                             
  OP_kernels[0].name      = name;                                                        
  OP_kernels[0].count    += 1;                                                           
  OP_kernels[0].time     += wall_t2 - wall_t1;                                           
  OP_kernels[0].transfer += (*Plan).transfer;                                            
}                                                                                        
                                                                                         
