// 
// auto-generated by op2.m on 11-Feb-2011 10:27:59 
//

// number of kernels        
                            
#define OP_KERNELS_MAX 2    
                            
// header                   
                            
#include "op_lib.cpp"       
                            
// global constants         
                            
extern double alpha;         
                            
// user kernel files        
                            
#include "res_kernel.cpp"   
#include "update_kernel.cpp"
