// 
// auto-generated by op2.m on 04-Aug-2010 11:26:18 
//

// user function                                                                  
                                                                                  
#include "save_soln.h"                                                            
                                                                                  
                                                                                  
// x86 kernel function                                                            
                                                                                  
void op_x86_save_soln(                                                            
  float *arg0,                                                                    
  float *arg1,                                                                    
  int   set_size ) {                                                              
                                                                                  
                                                                                  
  // process set elements                                                         
                                                                                  
  for (int n=0; n<set_size; n++) {                                                
                                                                                  
      // user-supplied kernel call                                                
                                                                                  
      save_soln( arg0+n*4,                                                        
                 arg1+n*4 );                                                      
  }                                                                               
}                                                                                 
                                                                                  
                                                                                  
// host stub function                                                             
                                                                                  
void op_par_loop_save_soln(char const *name, op_set set,                          
  op_dat arg0, int idx0, op_ptr ptr0, int dim0, char const *typ0, op_access acc0, 
  op_dat arg1, int idx1, op_ptr ptr1, int dim1, char const *typ1, op_access acc1){
                                                                                  
                                                                                  
  if (OP_DIAGS>1) {                                                               
    printf(" kernel routine w/o indirection:  save_soln \n");                     
  }                                                                               
                                                                                  
  // execute plan                                                                 
                                                                                  
  op_x86_save_soln( (float *) arg0.dat,                                           
                    (float *) arg1.dat,                                           
                    set.size );                                                   
}                                                                                 
                                                                                  
