// 
// auto-generated by op2.m on 04-Aug-2010 11:26:18 
//

// user function                                                                  
                                                                                  
__device__                                                                        
#include "save_soln.h"                                                            
                                                                                  
                                                                                  
// CUDA kernel function                                                           
                                                                                  
__global__ void op_cuda_save_soln(                                                
  float *arg0,                                                                    
  float *arg1,                                                                    
  int   set_size ) {                                                              
                                                                                  
                                                                                  
  // process set elements                                                         
                                                                                  
  for (int n=threadIdx.x+blockIdx.x*blockDim.x;                                   
       n<set_size; n+=blockDim.x*gridDim.x) {                                     
                                                                                  
      // user-supplied kernel call                                                
                                                                                  
      save_soln( arg0+n*4,                                                        
                 arg1+n*4 );                                                      
  }                                                                               
}                                                                                 
                                                                                  
                                                                                  
// host stub function                                                             
                                                                                  
void op_par_loop_save_soln(char const *name, op_set set,                          
  op_dat arg0, int idx0, op_ptr ptr0, int dim0, char const *typ0, op_access acc0, 
  op_dat arg1, int idx1, op_ptr ptr1, int dim1, char const *typ1, op_access acc1){
                                                                                  
                                                                                  
  if (OP_DIAGS>1) {                                                               
    printf(" kernel routine w/o indirection:  save_soln \n");                     
  }                                                                               
                                                                                  
  // execute plan                                                                 
                                                                                  
  op_cuda_save_soln<<<100,64>>>( (float *) arg0.dat_d,                            
                                 (float *) arg1.dat_d,                            
                                 set.size );                                      
                                                                                  
  cutilCheckMsg("op_cuda_save_soln execution failed\n");                          
}                                                                                 
                                                                                  
