// 
// auto-generated by op2.m on 21-Apr-2011 16:52:40 
//

// header                   
                            
#include "op_lib.h"         
                            
void __syncthreads(){}      
                            
// global constants         
                            
extern float alpha;         
                            
// user kernel files        
                            
#include "res_kernel.cpp"   
#include "update_kernel.cpp"
