// 
// auto-generated by op2.m on 20-Apr-2011 09:58:29 
//

// header                   
                            
#include "op_lib.cpp"       
                            
// global constants         
                            
extern float alpha;         
                            
// user kernel files        
                            
#include "res_kernel.cpp"   
#include "update_kernel.cpp"
