// 
// auto-generated by op2.m on 31-Oct-2010 15:01:48 
//

// header                   
                            
#include "op_lib.cpp"       
                            
// global constants         
                            
extern float alpha;         
                            
// user kernel files        
                            
#include "res_kernel.cpp"   
#include "update_kernel.cpp"
