// 
// auto-generated by op2.m on 16-Apr-2011 22:06:07 
//

// header                                                                                 
                                                                                          
#include "op_lib.cu"                                                                      
                                                                                          
// global constants                                                                       
                                                                                          
#ifndef MAX_CONST_SIZE                                                                    
#define MAX_CONST_SIZE 128                                                                
#endif                                                                                    
                                                                                          
__constant__ float alpha;                                                                 
                                                                                          
void op_decl_const_char(int dim, char const *type, int size, char *dat, char const *name){
  cutilSafeCall(cudaMemcpyToSymbol(name, dat, dim*size));                                 
}                                                                                         
                                                                                          
// user kernel files                                                                      
                                                                                          
#include "res_kernel.cu"                                                                  
#include "update_kernel.cu"                                                               
