// 
// auto-generated by op2.m on 31-Oct-2010 15:01:48 
//

// user function                                                                           
                                                                                           
__device__                                                                                 
#include "res.h"                                                                           
                                                                                           
                                                                                           
// CUDA kernel function                                                                    
                                                                                           
__global__ void op_cuda_res(                                                               
  float *ind_arg0, int *ind_arg0_ptrs, int *ind_arg0_sizes, int *ind_arg0_offset,          
  float *ind_arg1, int *ind_arg1_ptrs, int *ind_arg1_sizes, int *ind_arg1_offset,          
  double *arg0_d,                                                                          
  int   *arg1_ptrs,                                                                        
  int   *arg2_ptrs,                                                                        
  const float *arg3,                                                                       
  int    block_offset,                                                                     
  int   *blkmap,                                                                           
  int   *offset,                                                                           
  int   *nelems,                                                                           
  int   *ncolors,                                                                          
  int   *colors) {                                                                         
                                                                                           
  float arg2_l[3];                                                                         
                                                                                           
  __shared__ int   *ind_arg0_ptr, ind_arg0_size;                                           
  __shared__ int   *ind_arg1_ptr, ind_arg1_size;                                           
  __shared__ float *ind_arg0_s;                                                            
  __shared__ float *ind_arg1_s;                                                            
  __shared__ double *arg0;                                                                 
  __shared__ int   *arg1_ptr;                                                              
  __shared__ int   *arg2_ptr;                                                              
  __shared__ int    nelems2, ncolor, *color;                                               
  __shared__ int    blockId, nelem;                                                        
                                                                                           
  extern __shared__ char shared[];                                                         
                                                                                           
  if (threadIdx.x==0) {                                                                    
                                                                                           
    // get sizes and shift pointers and direct-mapped data                                 
                                                                                           
    blockId = blkmap[blockIdx.x + block_offset];                                           
    nelem   = nelems[blockId];                                                             
                                                                                           
    nelems2 = blockDim.x*(1+(nelem-1)/blockDim.x);                                         
    ncolor  = ncolors[blockId];                                                            
    color   = colors + offset[blockId];                                                    
                                                                                           
    ind_arg0_size = ind_arg0_sizes[blockId];                                               
    ind_arg1_size = ind_arg1_sizes[blockId];                                               
                                                                                           
    ind_arg0_ptr = ind_arg0_ptrs + ind_arg0_offset[blockId];                               
    ind_arg1_ptr = ind_arg1_ptrs + ind_arg1_offset[blockId];                               
                                                                                           
    arg0         = arg0_d    + offset[blockId]*3;                                          
    arg1_ptr     = arg1_ptrs + offset[blockId];                                            
    arg2_ptr     = arg2_ptrs + offset[blockId];                                            
                                                                                           
    // set shared memory pointers                                                          
                                                                                           
    int nbytes = 0;                                                                        
    ind_arg0_s = (float *) &shared[nbytes];                                                
    nbytes    += ROUND_UP(ind_arg0_size*sizeof(float)*2);                                  
    ind_arg1_s = (float *) &shared[nbytes];                                                
  }                                                                                        
                                                                                           
  __syncthreads(); // make sure all of above completed                                     
                                                                                           
  // copy indirect datasets into shared memory or zero increment                           
                                                                                           
  for (int n=threadIdx.x; n<ind_arg0_size; n+=blockDim.x)                                  
    for (int d=0; d<2; d++)                                                                
      ind_arg0_s[d+n*2] = ind_arg0[d+ind_arg0_ptr[n]*2];                                   
                                                                                           
  for (int n=threadIdx.x; n<ind_arg1_size; n+=blockDim.x)                                  
    for (int d=0; d<3; d++)                                                                
      ind_arg1_s[d+n*3] = ZERO_float;                                                      
                                                                                           
  __syncthreads();                                                                         
                                                                                           
  // process set elements                                                                  
                                                                                           
  for (int n=threadIdx.x; n<nelems2; n+=blockDim.x) {                                      
    int col2 = -1;                                                                         
                                                                                           
    if (n<nelem) {                                                                         
                                                                                           
      // initialise local variables                                                        
                                                                                           
      for (int d=0; d<3; d++)                                                              
        arg2_l[d] = ZERO_float;                                                            
                                                                                           
      // user-supplied kernel call                                                         
                                                                                           
      res( arg0+n*3,                                                                       
           ind_arg0_s+arg1_ptr[n]*2,                                                       
           arg2_l,                                                                         
           arg3 );                                                                         
                                                                                           
      col2 = color[n];                                                                     
    }                                                                                      
                                                                                           
    // store local variables                                                               
                                                                                           
    for (int col=0; col<ncolor; col++) {                                                   
      if (col2==col) {                                                                     
        for (int d=0; d<3; d++)                                                            
          ind_arg1_s[d+arg2_ptr[n]*3] += arg2_l[d];                                        
      }                                                                                    
      __syncthreads();                                                                     
    }                                                                                      
                                                                                           
  }                                                                                        
                                                                                           
  // apply pointered write/increment                                                       
                                                                                           
  for (int n=threadIdx.x; n<ind_arg1_size; n+=blockDim.x)                                  
    for (int d=0; d<3; d++)                                                                
      ind_arg1[d+ind_arg1_ptr[n]*3] += ind_arg1_s[d+n*3];                                  
                                                                                           
}                                                                                          
                                                                                           
                                                                                           
// host stub function                                                                      
                                                                                           
void op_par_loop_res(char const *name, op_set set,                                         
  op_dat arg0, int idx0, op_ptr ptr0, int dim0, char const *typ0, op_access acc0,          
  op_dat arg1, int idx1, op_ptr ptr1, int dim1, char const *typ1, op_access acc1,          
  op_dat arg2, int idx2, op_ptr ptr2, int dim2, char const *typ2, op_access acc2,          
  float *arg3h,int idx3, op_ptr ptr3, int dim3, char const *typ3, op_access acc3){         
                                                                                           
  op_dat arg3 = {{0,0,"null"},0,0,0,(char *)arg3h,NULL,"float","gbl"};                     
                                                                                           
  int         nargs = 4, ninds = 2;                                                        
                                                                                           
  op_dat      args[4] = {arg0,arg1,arg2,arg3};                                             
  int         idxs[4] = {idx0,idx1,idx2,idx3};                                             
  op_ptr      ptrs[4] = {ptr0,ptr1,ptr2,ptr3};                                             
  int         dims[4] = {dim0,dim1,dim2,dim3};                                             
  char const *typs[4] = {typ0,typ1,typ2,typ3};                                             
  op_access   accs[4] = {acc0,acc1,acc2,acc3};                                             
  int         inds[4] = {-1,0,1,-1};                                                       
                                                                                           
  if (OP_diags>2) {                                                                        
    printf(" kernel routine with indirection: res \n");                                    
  }                                                                                        
                                                                                           
  // initialise timers                                                                     
                                                                                           
  double cpu_t1, cpu_t2, wall_t1, wall_t2;                                                 
  timers(&cpu_t1, &wall_t1);                                                               
                                                                                           
  // transfer constants to GPU                                                             
                                                                                           
  int consts_bytes = 0;                                                                    
  consts_bytes += ROUND_UP(1*sizeof(float));                                               
                                                                                           
  reallocConstArrays(consts_bytes);                                                        
                                                                                           
  consts_bytes = 0;                                                                        
  arg3.dat   = OP_consts_h + consts_bytes;                                                 
  arg3.dat_d = OP_consts_d + consts_bytes;                                                 
  for (int d=0; d<1; d++) ((float *)arg3.dat)[d] = ((float *)arg3h)[d];                    
  consts_bytes += ROUND_UP(1*sizeof(float));                                               
                                                                                           
  mvConstArraysToDevice(consts_bytes);                                                     
                                                                                           
  // get plan                                                                              
                                                                                           
  op_plan *Plan = plan(name,set,nargs,args,idxs,ptrs,dims,typs,accs,ninds,inds);           
                                                                                           
  // execute plan                                                                          
                                                                                           
  int block_offset = 0;                                                                    
                                                                                           
  for (int col=0; col<(*Plan).ncolors; col++) {                                            
                                                                                           
    int nblocks = (*Plan).ncolblk[col];                                                    
    int nthread = OP_block_size;                                                           
    int nshared = (*Plan).nshared;                                                         
    op_cuda_res<<<nblocks,nthread,nshared>>>(                                              
       (float *)arg1.dat_d, (*Plan).ind_ptrs[0], (*Plan).ind_sizes[0], (*Plan).ind_offs[0],
       (float *)arg2.dat_d, (*Plan).ind_ptrs[1], (*Plan).ind_sizes[1], (*Plan).ind_offs[1],
       (double *)arg0.dat_d,                                                               
       (*Plan).ptrs[1],                                                                    
       (*Plan).ptrs[2],                                                                    
       (float *)arg3.dat_d,                                                                
       block_offset,                                                                       
       (*Plan).blkmap,                                                                     
       (*Plan).offset,                                                                     
       (*Plan).nelems,                                                                     
       (*Plan).nthrcol,                                                                    
       (*Plan).thrcol);                                                                    
                                                                                           
    cutilSafeCall(cudaThreadSynchronize());                                                
    cutilCheckMsg("op_cuda_res execution failed\n");                                       
                                                                                           
    block_offset += nblocks;                                                               
  }                                                                                        
                                                                                           
  // update kernel record                                                                  
                                                                                           
  timers(&cpu_t2, &wall_t2);                                                               
  OP_kernels[0].name      = name;                                                          
  OP_kernels[0].count    += 1;                                                             
  OP_kernels[0].time     += wall_t2 - wall_t1;                                             
  OP_kernels[0].transfer += (*Plan).transfer;                                              
}                                                                                          
                                                                                           
